repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-json
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: mixed-line-ending
    -   id: sort-simple-yaml
    -   id: requirements-txt-fixer
    -   id: pretty-format-json
        args: [--autofix]
-   repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
    -   id: flake8
-   repo: https://github.com/PyCQA/pylint
    rev: v4.0.6
    hooks:
    -   id: pylint
